package com.mahjoub.Gestiondestock.Exceptions;

public enum ErrorCode {
    ARTICLE_NOT_FOUND(1000),
    ARTICLE_NOT_VALID(1010),
    CATEGORIE_NOT_FOUND(2000),
    CATEGORIE_NOT_VALID(2002),
    //todo complete the rest of the error codes
    CLIENT_NOT_FOUND(3000),
    CLIENT_NOT_VALID(3001),
    FOURNISSEUR_NOT_FOUND(4000),
    FOURNISSEUR_NOT_VALID(4001),
    ENTREPRISE_NOT_FOUND(5000),
    ENTREPRISE_NOT_VALID(5001),
    COMMANDE_CLIENT_NOT_FOUND(3011),
    COMMANDE_CLIENT_NOT_VALID(3012),
    COMMANDE_FOURNISSEUR_NOT_FOUND(4001),
    COMMANDE_FOURNISSEUR_NOT_VALID(4002),
    LIGNE_COMMANDE_CLIENT_NOT_FOUND(3002),
    LIGNE_COMMANDE_FOURNISSEUR_NOT_FOUND(4002),
    UTILISATEUR_NOT_FOUND(1100),
    UTILISATEUR_NOT_VALID(1101),
    VENTE_NOT_FOUND(1200),
    VENTE_NOT_VALID(1201),
    LIGNE_VENTE_NOT_FOUND(1500),
    LIGNE_VENTE_NOT_VALID(1501),
    MVTSTK_NOT_FOUND(1300),
    MVTSTK_NOT_VALID(1301),
    ;
    private int code;

    ErrorCode(int code) {
        this.code = code;
    }

    public int getCode() {
        return code;
    }
}
